### PR TITLE
A few improvements...

### PR DESCRIPTION
**Pull request by aidan-casey**
Hey there!

I hope you are doing well. I stumbled across this `unfinalize` package and noticed a few areas for improvement so I wanted to help the community and create a PR.

Feel free to review and merge when you're ready to embrace the final frontier of coding perfection!

Yours in finality,
Aidan

### CODE REVIEW

**Comment by stevebauman** [comment]
Thanks @aidan-casey! This is a 🔥 PR and I appreciate your time, but I simply cannot humbly accept such an improvement ❤️

**Comment by aidan-casey** [comment]
Thanks for taking the time to review, @stevebauman! While I respect your stance, I have to admit it is a little disappointing. This is your final decision?

**Comment by stevebauman** [comment]
No problem @aidan-casey! No nothing is ever final. Once the keyword allows inheritance, I'll merge this PR 👍

**Comment by Wirone** [comment]
@stevebauman can't you just bypass it while reading?

**Pull request closed without merging**
